# Generated by Django 4.1.1 on 2022-10-03 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('battle_map', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_player2', to=settings.AUTH_USER_MODEL)),
                ('spectators', models.ManyToManyField(related_name='viewed_game', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='signed_game', to=settings.AUTH_USER_MODEL)),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
